import { createBrowserRouter, Navigate } from "react-router-dom";

import {
  PatientClinicalPage,
  PatientDetailPage,
  PatientDocumentsPage,
  PatientFormPage,
  PatientHistoryPage,
  PatientsListPage,
  CheckInPage,
  ReceptionDashboardPage,
  ReceptionWorkflowPage,
  ReferralPage,
  WaitingQueuePage,
  PendingLabOrdersPage,
  ConsultationDashboardPage,
  ConsultationDetailPage,
  ConsultationHistoryPage,
  ConsultationQueuePage,
  AppointmentDetailPage,
  AppointmentEditPage,
  AppointmentFormPage,
  AppointmentsCalendarPage,
  AppointmentsDashboardPage,
  AppointmentsListPage,
  AppointmentsQueuePage,
  LaboratoryCollectionPage,
  LaboratoryDashboardPage,
  LaboratoryDetailPage,
  LaboratoryPendingPage,
  LaboratoryTodayPage,
  ResultCreatePage,
  ResultDetailPage,
  ResultEditPage,
  ResultHistoryPage,
  ResultsDashboardPage,
  BillingDashboardPage,
  InvoiceCreatePage,
  PendingReductionsPage,
  UrgentStockPage,
  UrgentStockHistoryPage,
  InvoiceDetailPage,
  InvoicesListPage,
  BillingPatientHistoryPage,
  PaymentsListPage,
  QuoteCreatePage,
  QuotesListPage,
  ReceiptDetailPage,
  ReceiptsListPage,
  ServiceDetailPage,
  ServiceFormPage,
  ServicesListPage,
  CashMovementsPage,
  CashRegisterDetailPage,
  CashRegistersPage,
  ExpenseFormPage,
  ExpensesPage,
  FinanceDashboardPage,
  FinanceReportsPage,
  AppointmentsReportPage,
  BillingReportPage,
  ExecutiveReportPage,
  FinanceReportPage,
  LaboratoryReportPage,
  PatientsReportPage,
  ReportsDashboardPage,
  BackupPage,
  BillingSettingsPage,
  ClinicSettingsPage,
  ConsultationTypesPage,
  DepartmentsPage,
  EmailSettingsPage,
  FeatureFlagsPage,
  LaboratorySettingsPage,
  RoomsPage,
  SecuritySettingsPage,
  SettingsDashboardPage,
  SpecialtiesPage,
  SystemStatusPage,
  WorkingHoursPage,
  MedicoProfilesPage,
  ClinicalEvolutionPage,
  DischargePage,
  DoctorDashboardPage,
  HistoryPage,
  PrescriptionsPage,
  TreatmentsPage,
  EmailHistoryPage,
  NotificationCenterPage,
  NotificationsDashboardPage,
  PreferencesPage,
  SMSHistoryPage,
  TemplatesPage,
  AdminDashboardPage,
  AuditPage,
  GroupsPage,
  PermissionsPage,
  ProfilePage,
  UserFormPage,
  UsersListPage,
  LoginPage,
  NotFoundPage,
  AdminRoleDashboardPage,
  DirectorRoleDashboardPage,
  DoctorRoleDashboardPage,
  LaboratoryRoleDashboardPage,
  NurseTriagePage,
  NurseRoleDashboardPage,
  ReceptionRoleDashboardPage,
} from "@/routes/pages.lazy";

import { AdminLayout } from "@/layouts/AdminLayout";
import { AppLayout } from "@/layouts/AppLayout";
import { AuthLayout } from "@/layouts/AuthLayout";
import { ProtectedRoute, PublicRoute, PermissionRoute, PermissionGuard, AdminOnlyRoute } from "@/routes/guards";
import { RoleGuard } from "@/routes/RoleGuard";
import { RoleHomeRedirect } from "@/routes/RoleHomeRedirect";

export const router = createBrowserRouter([
  {
    element: <ProtectedRoute />,
    children: [
      {
        element: <AppLayout />,
        children: [
          { index: true, element: <RoleHomeRedirect /> },
          { path: "dashboard/admin", element: <RoleGuard allowed="ADMINISTRADOR"><AdminRoleDashboardPage /></RoleGuard> },
          { path: "dashboard/director", element: <RoleGuard allowed="DIRECTOR"><DirectorRoleDashboardPage /></RoleGuard> },
          { path: "dashboard/doctor", element: <RoleGuard allowed="MEDICO"><DoctorRoleDashboardPage /></RoleGuard> },
          { path: "dashboard/reception", element: <RoleGuard allowed="RECECIONISTA"><ReceptionRoleDashboardPage /></RoleGuard> },
          { path: "dashboard/laboratory", element: <RoleGuard allowed="LABORATORIO"><LaboratoryRoleDashboardPage /></RoleGuard> },
          { path: "dashboard/nurse", element: <RoleGuard allowed="ENFERMEIRO"><NurseRoleDashboardPage /></RoleGuard> },
          {
            element: (
              <RoleGuard allowed="ENFERMEIRO">
                <PermissionRoute permission="reception.create" fallback="/" />
              </RoleGuard>
            ),
            children: [{ path: "nursing/triage", element: <NurseTriagePage /> }],
          },
          {
            element: <PermissionRoute permission="patients.view" fallback="/" />,
            children: [
              { path: "patients", element: <PatientsListPage /> },
              { path: "patients/:id/edit", element: <PatientFormPage /> },
              { path: "patients/:id/clinical", element: <PatientClinicalPage /> },
              { path: "patients/:id/documents", element: <PatientDocumentsPage /> },
              { path: "patients/:id/history", element: <PatientHistoryPage /> },
              { path: "patients/:id", element: <PatientDetailPage /> },
            ],
          },
          {
            element: (
              <RoleGuard allowed={["RECECIONISTA", "ADMINISTRADOR"]}>
                <PermissionRoute permission="reception.view" />
              </RoleGuard>
            ),
            children: [
              { path: "reception", element: <ReceptionDashboardPage /> },
              { path: "reception/atendimento", element: <ReceptionWorkflowPage /> },
              { path: "reception/check-in", element: <CheckInPage /> },
              { path: "reception/queue", element: <WaitingQueuePage /> },
              { path: "reception/lab-orders", element: <PendingLabOrdersPage /> },
              { path: "reception/referrals", element: <ReferralPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="appointments.view" fallback="/" />,
            children: [
              { path: "appointments", element: <AppointmentsDashboardPage /> },
              { path: "appointments/calendar", element: <AppointmentsCalendarPage /> },
              { path: "appointments/list", element: <AppointmentsListPage /> },
              { path: "appointments/queue", element: <AppointmentsQueuePage /> },
              { path: "appointments/new", element: <AppointmentFormPage /> },
              { path: "appointments/:id/edit", element: <AppointmentEditPage /> },
              { path: "appointments/:id", element: <AppointmentDetailPage /> },
              { path: "consultations", element: <ConsultationDashboardPage /> },
              { path: "consultations/queue", element: <ConsultationQueuePage /> },
              { path: "consultations/history", element: <ConsultationHistoryPage /> },
              { path: "consultations/:id", element: <ConsultationDetailPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="laboratory.view" fallback="/" />,
            children: [
              { path: "laboratory", element: <LaboratoryDashboardPage /> },
              { path: "laboratory/pending", element: <LaboratoryPendingPage /> },
              { path: "laboratory/today", element: <LaboratoryTodayPage /> },
              { path: "laboratory/collection", element: <LaboratoryCollectionPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="laboratory.results.view" fallback="/" />,
            children: [
              { path: "laboratory/results", element: <ResultsDashboardPage /> },
              { path: "laboratory/results/history", element: <ResultHistoryPage /> },
              { path: "laboratory/results/new", element: <ResultCreatePage /> },
              { path: "laboratory/results/:id/edit", element: <ResultEditPage /> },
              { path: "laboratory/results/:id", element: <ResultDetailPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="laboratory.view" fallback="/" />,
            children: [
              { path: "laboratory/:id", element: <LaboratoryDetailPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="billing.view" fallback="/" />,
            children: [
              { path: "billing", element: <BillingDashboardPage /> },
              { path: "billing/services", element: <ServicesListPage /> },
              { path: "billing/services/:id", element: <ServiceDetailPage /> },
              { path: "billing/quotes", element: <QuotesListPage /> },
              { path: "billing/invoices", element: <InvoicesListPage /> },
              { path: "billing/reducoes/pendentes", element: <PendingReductionsPage /> },
              { path: "billing/payments", element: <PaymentsListPage /> },
              { path: "billing/receipts", element: <ReceiptsListPage /> },
              { path: "billing/history", element: <BillingPatientHistoryPage /> },
              { path: "billing/receipts/:id", element: <ReceiptDetailPage /> },
              { path: "billing/invoices/:id", element: <InvoiceDetailPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="billing.delete" fallback="/billing/services" />,
            children: [
              { path: "billing/services/new", element: <ServiceFormPage /> },
              { path: "billing/services/:id/edit", element: <ServiceFormPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="billing.quote" fallback="/billing" />,
            children: [{ path: "billing/quotes/new", element: <QuoteCreatePage /> }],
          },
          {
            element: <PermissionRoute permission="billing.create" fallback="/billing" />,
            children: [{ path: "billing/invoices/new", element: <InvoiceCreatePage /> }],
          },
          {
            element: <PermissionRoute permission="finance.view" fallback="/" />,
            children: [
              { path: "finance", element: <FinanceDashboardPage /> },
              { path: "finance/cash", element: <CashRegistersPage /> },
              { path: "finance/cash/:id", element: <CashRegisterDetailPage /> },
              { path: "finance/movements", element: <CashMovementsPage /> },
              { path: "finance/expenses", element: <ExpensesPage /> },
              { path: "finance/reports", element: <FinanceReportsPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="finance.create" fallback="/finance/expenses" />,
            children: [{ path: "finance/expenses/new", element: <ExpenseFormPage /> }],
          },
          {
            element: <PermissionRoute permission="pharmacy.view" fallback="/" />,
            children: [
              { path: "stock", element: <UrgentStockPage /> },
              { path: "stock/historico", element: <UrgentStockHistoryPage /> },
              { path: "pharmacy/urgent-stock", element: <UrgentStockPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="reports.view" fallback="/" />,
            children: [
              { path: "reports", element: <ReportsDashboardPage /> },
              { path: "reports/patients", element: <PatientsReportPage /> },
              { path: "reports/appointments", element: <AppointmentsReportPage /> },
              { path: "reports/laboratory", element: <LaboratoryReportPage /> },
              { path: "reports/billing", element: <BillingReportPage /> },
              { path: "reports/finance", element: <FinanceReportPage /> },
              { path: "reports/executive", element: <ExecutiveReportPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="settings.view" fallback="/" />,
            children: [
              { path: "settings", element: <SettingsDashboardPage /> },
              { path: "settings/clinic", element: <ClinicSettingsPage /> },
              { path: "settings/departments", element: <DepartmentsPage /> },
              { path: "settings/specialties", element: <SpecialtiesPage /> },
              { path: "settings/medicos", element: <MedicoProfilesPage /> },
              { path: "settings/rooms", element: <RoomsPage /> },
              { path: "settings/hours", element: <WorkingHoursPage /> },
              { path: "settings/consultation-types", element: <ConsultationTypesPage /> },
              { path: "settings/laboratory", element: <LaboratorySettingsPage /> },
              { path: "settings/billing", element: <BillingSettingsPage /> },
              { path: "settings/email", element: <EmailSettingsPage /> },
              { path: "settings/security", element: <SecuritySettingsPage /> },
              { path: "settings/backups", element: <BackupPage /> },
              { path: "settings/system", element: <SystemStatusPage /> },
              { path: "settings/feature-flags", element: <FeatureFlagsPage /> },
            ],
          },
          {
            element: <PermissionRoute permission="doctors.prescription" fallback="/" />,
            children: [
              { path: "doctor", element: <DoctorDashboardPage /> },
              { path: "doctor/prescriptions", element: <PrescriptionsPage /> },
              { path: "doctor/treatments", element: <TreatmentsPage /> },
              { path: "doctor/evolution", element: <ClinicalEvolutionPage /> },
              { path: "doctor/history", element: <HistoryPage /> },
              { path: "doctor/discharge", element: <DischargePage /> },
            ],
          },
          {
            element: <PermissionRoute permission="notifications.view" fallback="/" />,
            children: [
              { path: "notifications", element: <NotificationCenterPage /> },
              { path: "notifications/history", element: <EmailHistoryPage /> },
              { path: "notifications/sms", element: <SMSHistoryPage /> },
              { path: "notifications/templates", element: <TemplatesPage /> },
              { path: "notifications/preferences", element: <PreferencesPage /> },
              { path: "notifications/dashboard", element: <NotificationsDashboardPage /> },
            ],
          },
          {
            path: "patients/new",
            element: (
              <PermissionGuard permission="patients.create" fallback="/patients">
                <PatientFormPage />
              </PermissionGuard>
            ),
          },
          {
            path: "admin",
            element: <AdminOnlyRoute />,
            children: [
              {
                element: <AdminLayout />,
                children: [
              { index: true, element: <Navigate to="dashboard" replace /> },
              { path: "dashboard", element: <AdminDashboardPage /> },
              { path: "users", element: <UsersListPage /> },
              { path: "users/new", element: <UserFormPage /> },
              { path: "users/:id/edit", element: <UserFormPage /> },
              { path: "permissions", element: <PermissionsPage /> },
              { path: "groups", element: <GroupsPage /> },
              { path: "audit", element: <AuditPage /> },
              { path: "profile", element: <ProfilePage /> },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    element: <PublicRoute />,
    children: [
      {
        element: <AuthLayout />,
        children: [{ path: "login", element: <LoginPage /> }],
      },
    ],
  },
  { path: "/404", element: <NotFoundPage /> },
  { path: "*", element: <NotFoundPage /> },
]);
