# Generated by Django 5.1.15 on 2026-07-06 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.SlugField(max_length=80, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('variaveis', models.JSONField(blank=True, default=list, verbose_name='Variáveis disponíveis')),
            ],
            options={
                'verbose_name': 'Template de e-mail',
                'verbose_name_plural': 'Templates de e-mail',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.SlugField(max_length=80, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('variaveis', models.JSONField(blank=True, default=list, verbose_name='Variáveis disponíveis')),
            ],
            options={
                'verbose_name': 'Template SMS',
                'verbose_name_plural': 'Templates SMS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('SUCESSO', 'Sucesso'), ('AVISO', 'Aviso'), ('ERRO', 'Erro'), ('LEMBRETE', 'Lembrete'), ('URGENTE', 'Urgente')], default='INFORMATIVA', max_length=20, verbose_name='Tipo')),
                ('canal', models.CharField(choices=[('INTERNO', 'Interno'), ('EMAIL', 'E-mail'), ('SMS', 'SMS')], default='INTERNO', max_length=20, verbose_name='Canal')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'A processar'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Estado')),
                ('evento_origem', models.CharField(blank=True, max_length=100, verbose_name='Evento de origem')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('arquivada', models.BooleanField(default=False, verbose_name='Arquivada')),
                ('destinatario_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail destinatário')),
                ('destinatario_telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone destinatário')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'A processar'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='ENVIADA', max_length=20, verbose_name='Estado')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='notifications.notificacao', verbose_name='Notificação')),
            ],
            options={
                'verbose_name': 'Histórico SMS',
                'verbose_name_plural': 'Histórico SMS',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Destinatário')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'A processar'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='ENVIADA', max_length=20, verbose_name='Estado')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='notifications.notificacao', verbose_name='Notificação')),
            ],
            options={
                'verbose_name': 'Histórico de e-mail',
                'verbose_name_plural': 'Histórico de e-mails',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='FilaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('prioridade', models.PositiveSmallIntegerField(default=5, verbose_name='Prioridade')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('max_tentativas', models.PositiveSmallIntegerField(default=3, verbose_name='Máximo de tentativas')),
                ('agendado_para', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila', to='notifications.notificacao', verbose_name='Notificação')),
            ],
            options={
                'verbose_name': 'Fila de notificação',
                'verbose_name_plural': 'Fila de notificações',
                'ordering': ['prioridade', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('receber_email', models.BooleanField(default=True, verbose_name='Receber e-mail')),
                ('receber_sms', models.BooleanField(default=False, verbose_name='Receber SMS')),
                ('receber_internas', models.BooleanField(default=True, verbose_name='Receber notificações internas')),
                ('receber_lembretes', models.BooleanField(default=True, verbose_name='Receber lembretes')),
                ('receber_alertas_admin', models.BooleanField(default=True, verbose_name='Receber alertas administrativos')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificação',
            },
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['utilizador', 'lida', 'arquivada'], name='notificatio_utiliza_ebbc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['estado'], name='notificatio_estado_7ea6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['canal'], name='notificatio_canal_8e2741_idx'),
        ),
    ]
