# Generated by Django 5.1.15 on 2026-07-04 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('scheduled_at', models.DateTimeField(verbose_name='Data/hora agendada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da consulta')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim da consulta')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('CONFIRMED', 'Confirmada'), ('IN_PROGRESS', 'Em curso'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'Falta')], default='SCHEDULED', max_length=20, verbose_name='Estado')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Queixa principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='Notas clínicas')),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='reception.receptioncheckin', verbose_name='Check-in')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='Paciente')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='reception.referral', verbose_name='Encaminhamento')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['patient', 'scheduled_at'], name='idx_appt_patient_date'), models.Index(fields=['patient', 'status'], name='idx_appt_patient_status'), models.Index(fields=['doctor', 'status'], name='idx_appt_doctor_status'), models.Index(fields=['status', 'scheduled_at'], name='idx_appt_status_date')],
            },
        ),
    ]
