# Generated by Django 5.1.15 on 2026-07-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número da consulta'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da consulta'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('EMERGENCY', 'Emergência')], default='NORMAL', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='reception.waitingqueue', verbose_name='Entrada na fila'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='receptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_receptionist', to=settings.AUTH_USER_MODEL, verbose_name='Rececionista'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='chief_complaint',
            field=models.TextField(blank=True, verbose_name='Motivo da consulta'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de fim'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='Data/hora da consulta'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EM_ESPERA', 'Em espera'), ('EM_CONSULTA', 'Em consulta'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('FALTA', 'Falta')], default='AGENDADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['consultation_date', 'doctor'], name='idx_appt_date_doctor'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_number'], name='idx_appt_number'),
        ),
    ]
