# Generated by Django 5.1.15 on 2026-07-06 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_migrate_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subjetivo', models.TextField(blank=True, verbose_name='Subjetivo (S)')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo (O)')),
                ('avaliacao', models.TextField(blank=True, verbose_name='Avaliação (A)')),
                ('plano', models.TextField(blank=True, verbose_name='Plano (P)')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anotacao_soap', to='appointments.appointment', verbose_name='Consulta')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes_clinicas', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Anotação clínica (SOAP)',
                'verbose_name_plural': 'Anotações clínicas (SOAP)',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo_cid10', models.CharField(max_length=20, verbose_name='Código CID-10')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIO', 'Secundário')], default='PRINCIPAL', max_length=20, verbose_name='Tipo')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='appointments.appointment', verbose_name='Consulta')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_registados', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoImagiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_exame', models.CharField(max_length=150, verbose_name='Tipo de exame')),
                ('prioridade', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('EMERGENCY', 'Emergência')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Estado')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_imagiologia', to='appointments.appointment', verbose_name='Consulta')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_imagiologia_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Pedido de imagiologia',
                'verbose_name_plural': 'Pedidos de imagiologia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_exame', models.CharField(max_length=150, verbose_name='Tipo de exame')),
                ('prioridade', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('EMERGENCY', 'Emergência')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Estado')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_laboratorio', to='appointments.appointment', verbose_name='Consulta')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_laboratorio_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Pedido de laboratório',
                'verbose_name_plural': 'Pedidos de laboratório',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seguimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_retorno', models.DateField(verbose_name='Data de retorno')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimento', to='appointments.appointment', verbose_name='Consulta')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimentos_registados', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Seguimento',
                'verbose_name_plural': 'Seguimentos',
            },
        ),
        migrations.CreateModel(
            name='SinaisVitais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pressao_arterial', models.CharField(blank=True, max_length=20, verbose_name='Pressão arterial')),
                ('frequencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frequência cardíaca (bpm)')),
                ('frequencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frequência respiratória (rpm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('saturacao_oxigenio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Saturação de oxigénio (%)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinais_vitais', to='appointments.appointment', verbose_name='Consulta')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinais_vitais_registados', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Sinais vitais',
                'verbose_name_plural': 'Sinais vitais',
            },
        ),
    ]
