# Generated by Django 5.1.15 on 2026-08-25 01:49
# Idempotente: coluna pode já existir em bases de desenvolvimento/teste (Sprint 24/25).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_pce_fase2"),
        ("billing", "0007_catalogo_v1_codigo_length"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="pedidolaboratorio",
                    name="estado_faturacao",
                    field=models.CharField(
                        choices=[
                            ("AGUARDA_REGULARIZACAO", "Aguarda regularização"),
                            ("REGULARIZADO", "Regularizado"),
                            ("NAO_APLICAVEL", "Não aplicável"),
                        ],
                        default="AGUARDA_REGULARIZACAO",
                        max_length=30,
                        verbose_name="Estado de faturação",
                    ),
                ),
                migrations.AddField(
                    model_name="pedidolaboratorio",
                    name="servico",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_laboratorio_clinicos",
                        to="billing.servico",
                        verbose_name="Serviço",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE appointments_pedidolaboratorio
                      ADD COLUMN IF NOT EXISTS estado_faturacao varchar(30)
                        NOT NULL DEFAULT 'AGUARDA_REGULARIZACAO';
                    ALTER TABLE appointments_pedidolaboratorio
                      ADD COLUMN IF NOT EXISTS servico_id bigint NULL;
                    DO $$
                    BEGIN
                      IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'appointments_pedidolaboratorio_servico_id_fk'
                      ) THEN
                        ALTER TABLE appointments_pedidolaboratorio
                          ADD CONSTRAINT appointments_pedidolaboratorio_servico_id_fk
                          FOREIGN KEY (servico_id) REFERENCES billing_servico(id)
                          DEFERRABLE INITIALLY DEFERRED;
                      END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
