# Generated by Django 5.1.15 on 2026-07-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('patients', 'Pacientes'), ('appointments', 'Consultas'), ('laboratory', 'Laboratório'), ('billing', 'Faturação'), ('reports', 'Relatórios'), ('dashboard', 'Dashboard'), ('users', 'Utilizadores'), ('settings', 'Configurações')], max_length=50, verbose_name='Módulo')),
                ('action', models.CharField(choices=[('view', 'Visualizar'), ('create', 'Criar'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('print', 'Imprimir'), ('admin', 'Administrar')], max_length=20, verbose_name='Ação')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_system', models.BooleanField(default=False, verbose_name='Perfil do sistema')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.modulepermission', verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('members', models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='users.modulepermission', verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_jti', models.CharField(blank=True, max_length=255, verbose_name='JTI do refresh token')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sessão ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última atividade')),
                ('logged_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-last_activity'],
            },
        ),
    ]
