# Generated by Django 5.1.15 on 2026-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizar'), ('create', 'Criar'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('print', 'Imprimir'), ('admin', 'Administrar'), ('confirm', 'Confirmar'), ('start', 'Iniciar'), ('finish', 'Concluir'), ('cancel', 'Cancelar')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('patients', 'Pacientes'), ('appointments', 'Consultas'), ('laboratory', 'Laboratório'), ('billing', 'Faturação'), ('reports', 'Relatórios'), ('dashboard', 'Dashboard'), ('users', 'Utilizadores'), ('settings', 'Configurações'), ('reception', 'Receção')], max_length=50, verbose_name='Módulo'),
        ),
    ]
