# Generated by Django 5.1.15 on 2026-07-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_modulepermission_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizar'), ('create', 'Criar'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('print', 'Imprimir'), ('admin', 'Administrar'), ('confirm', 'Confirmar'), ('start', 'Iniciar'), ('finish', 'Concluir'), ('cancel', 'Cancelar'), ('clinical', 'Prontuário clínico'), ('diagnosis', 'Diagnósticos'), ('request_lab', 'Pedidos laboratório'), ('request_imaging', 'Pedidos imagiologia'), ('followup', 'Seguimento')], max_length=20, verbose_name='Ação'),
        ),
    ]
