# Generated by Django 5.1.15 on 2026-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sprint8_fase2_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizar'), ('create', 'Criar'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('print', 'Imprimir'), ('admin', 'Administrar'), ('confirm', 'Confirmar'), ('start', 'Iniciar'), ('finish', 'Concluir'), ('cancel', 'Cancelar'), ('clinical', 'Prontuário clínico'), ('diagnosis', 'Diagnósticos'), ('request_lab', 'Pedidos laboratório'), ('request_imaging', 'Pedidos imagiologia'), ('followup', 'Seguimento'), ('receive', 'Receber'), ('collect', 'Colheita'), ('process', 'Processar'), ('results.view', 'Ver resultados'), ('results.create', 'Criar resultados'), ('results.edit', 'Editar resultados'), ('results.validate', 'Validar resultados'), ('results.publish', 'Publicar resultados'), ('results.download', 'Descarregar resultados'), ('payment', 'Pagamentos'), ('receipt', 'Recibos'), ('quote', 'Orçamentos'), ('cash', 'Caixa'), ('expense', 'Despesas'), ('report', 'Relatórios'), ('dashboard', 'Dashboard financeiro'), ('statistics', 'Estatísticas')], max_length=20, verbose_name='Ação'),
        ),
    ]
