# Generated by Django 5.1.15 on 2026-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sprint11_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('patients', 'Pacientes'), ('appointments', 'Consultas'), ('laboratory', 'Laboratório'), ('billing', 'Faturação'), ('finance', 'Financeiro'), ('reports', 'Relatórios'), ('dashboard', 'Dashboard'), ('users', 'Utilizadores'), ('settings', 'Configurações'), ('reception', 'Receção'), ('doctors', 'Médicos')], max_length=50, verbose_name='Módulo'),
        ),
    ]
