# Generated by Django 5.1.15 on 2026-07-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATE', 'Criação de utilizador'), ('USER_UPDATE', 'Edição de utilizador'), ('USER_DELETE', 'Eliminação de utilizador'), ('USER_ACTIVATE', 'Ativação de utilizador'), ('USER_DEACTIVATE', 'Desativação de utilizador'), ('PASSWORD_CHANGE', 'Alteração de palavra-passe'), ('PERMISSION_CHANGE', 'Mudança de permissões'), ('ROLE_CHANGE', 'Mudança de perfil'), ('GROUP_CREATE', 'Criação de grupo'), ('GROUP_UPDATE', 'Edição de grupo'), ('GROUP_DELETE', 'Eliminação de grupo'), ('PROFILE_UPDATE', 'Atualização de perfil')], max_length=50, verbose_name='Ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de recurso')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID do recurso')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Registo de auditoria',
                'verbose_name_plural': 'Registos de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['created_at'], name='audit_logs__created_0fc90a_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs__user_id_d31e2a_idx')],
            },
        ),
    ]
