# Generated by Django 5.1.15 on 2026-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0004_sprint7_fase2_resultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATE', 'Criação de utilizador'), ('USER_UPDATE', 'Edição de utilizador'), ('USER_DELETE', 'Eliminação de utilizador'), ('USER_ACTIVATE', 'Ativação de utilizador'), ('USER_DEACTIVATE', 'Desativação de utilizador'), ('PASSWORD_CHANGE', 'Alteração de palavra-passe'), ('PERMISSION_CHANGE', 'Mudança de permissões'), ('ROLE_CHANGE', 'Mudança de perfil'), ('GROUP_CREATE', 'Criação de grupo'), ('GROUP_UPDATE', 'Edição de grupo'), ('GROUP_DELETE', 'Eliminação de grupo'), ('PROFILE_UPDATE', 'Atualização de perfil'), ('PATIENT_CREATE', 'Criação de paciente'), ('PATIENT_UPDATE', 'Edição de paciente'), ('PATIENT_DELETE', 'Eliminação de paciente'), ('PATIENT_ACTIVATE', 'Ativação de paciente'), ('PATIENT_DEACTIVATE', 'Desativação de paciente'), ('PATIENT_EXPORT', 'Exportação de pacientes'), ('PATIENT_PRINT', 'Impressão de ficha'), ('RECEPTION_CHECK_IN', 'Check-in na receção'), ('RECEPTION_STATUS_CHANGE', 'Alteração de estado na receção'), ('RECEPTION_ASSIGN_DOCTOR', 'Encaminhamento para médico'), ('RECEPTION_REFERRAL', 'Encaminhamento departamental'), ('RECEPTION_CANCEL', 'Cancelamento na receção'), ('APPOINTMENT_CREATE', 'Criação de consulta'), ('APPOINTMENT_START', 'Início de consulta'), ('APPOINTMENT_UPDATE', 'Actualização de consulta'), ('APPOINTMENT_COMPLETE', 'Conclusão de consulta'), ('APPOINTMENT_CANCEL', 'Cancelamento de consulta'), ('CONSULTA_CRIADA', 'Consulta criada'), ('CONSULTA_CONFIRMADA', 'Consulta confirmada'), ('CONSULTA_REAGENDADA', 'Consulta reagendada'), ('CONSULTA_INICIADA', 'Consulta iniciada'), ('CONSULTA_CONCLUIDA', 'Consulta concluída'), ('CONSULTA_CANCELADA', 'Consulta cancelada'), ('CONSULTA_CLINICA_EDITADA', 'Prontuário clínico editado'), ('SINAIS_VITAIS_REGISTADOS', 'Sinais vitais registados'), ('DIAGNOSTICO_ADICIONADO', 'Diagnóstico adicionado'), ('PEDIDO_LABORATORIO', 'Pedido de laboratório'), ('PEDIDO_IMAGIOLOGIA', 'Pedido de imagiologia'), ('SEGUIMENTO_AGENDADO', 'Seguimento agendado'), ('PEDIDO_LABORATORIO_RECEBIDO', 'Pedido laboratorial recebido'), ('COLHEITA_REALIZADA', 'Colheita realizada'), ('EXAME_INICIADO', 'Exame iniciado'), ('EXAME_CONCLUIDO', 'Exame concluído'), ('RESULTADO_CRIADO', 'Resultado laboratorial criado'), ('RESULTADO_EDITADO', 'Resultado laboratorial editado'), ('RESULTADO_VALIDADO', 'Resultado laboratorial validado'), ('RESULTADO_PUBLICADO', 'Resultado laboratorial publicado'), ('RESULTADO_DOWNLOAD', 'Download de resultado'), ('ANEXO_RESULTADO', 'Anexo de resultado'), ('ORCAMENTO_CRIADO', 'Orçamento criado'), ('ORCAMENTO_APROVADO', 'Orçamento aprovado'), ('FACTURA_CRIADA', 'Fatura criada'), ('FACTURA_CANCELADA', 'Fatura cancelada'), ('PAGAMENTO_REALIZADO', 'Pagamento realizado'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('RECIBO_EMITIDO', 'Recibo emitido')], max_length=50, verbose_name='Ação'),
        ),
    ]
