# Generated by Django 5.1.15 on 2026-07-06 10:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_pce_fase2'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('EXPIRADO', 'Expirado')], default='RASCUNHO', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto')),
                ('imposto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Imposto')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto')),
                ('imposto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Imposto')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('emitida_em', models.DateTimeField(blank=True, null=True, verbose_name='Emitida em')),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='appointments.appointment', verbose_name='Consulta')),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='patients.patient', verbose_name='Paciente')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='billing.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('metodo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO', 'Cartão'), ('MOBILE_MONEY', 'Mobile Money'), ('OUTRO', 'Outro')], default='DINHEIRO', max_length=20, verbose_name='Método de pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('CONFIRMADO', 'Confirmado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDENTE', max_length=20, verbose_name='Estado')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='billing.fatura', verbose_name='Fatura')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('emitido_em', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recibo', to='billing.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame'), ('PROCEDIMENTO', 'Procedimento'), ('INTERNAMENTO', 'Internamento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['activo', 'categoria'], name='idx_bill_svc_act_cat')],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='billing.orcamento', verbose_name='Orçamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='billing.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Item de orçamento',
                'verbose_name_plural': 'Itens de orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='billing.fatura', verbose_name='Fatura')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_fatura', to='billing.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Item de fatura',
                'verbose_name_plural': 'Itens de fatura',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['estado', 'created_at'], name='idx_bill_orc_estado'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['paciente', 'created_at'], name='idx_bill_orc_paciente'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['estado', 'emitida_em'], name='idx_bill_fat_estado'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['paciente', 'emitida_em'], name='idx_bill_fat_paciente'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['estado', 'data_pagamento'], name='idx_bill_pay_estado'),
        ),
    ]
