# Generated by Django 5.1.15 on 2026-07-31 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_sprint8_fase1_billing'),
        ('clinic_settings', '0002_sprint10_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoPrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço anterior')),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço novo')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('origem', models.CharField(default='manual', max_length=30, verbose_name='Origem')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Histórico de preço',
                'verbose_name_plural': 'Histórico de preços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='servico',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='servico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='servico',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='clinic_settings.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='servico',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='clinic_settings.especialidademedica', verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exige_agendamento',
            field=models.BooleanField(default=False, verbose_name='Exige agendamento'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exige_pagamento_antecipado',
            field=models.BooleanField(default=False, verbose_name='Exige pagamento antecipado'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exige_pedido_medico',
            field=models.BooleanField(default=False, verbose_name='Exige pedido médico'),
        ),
        migrations.AddField(
            model_name='servico',
            name='gera_resultado',
            field=models.BooleanField(default=False, verbose_name='Gera resultado'),
        ),
        migrations.AddField(
            model_name='servico',
            name='moeda',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='servico',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='servico',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='servico',
            name='permite_pagamento_parcial',
            field=models.BooleanField(default=True, verbose_name='Permite pagamento parcial'),
        ),
        migrations.AddField(
            model_name='servico',
            name='unidade_cobranca',
            field=models.CharField(default='unidade', max_length=30, verbose_name='Unidade de cobrança'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('LABORATORIO', 'Laboratório'), ('ECOGRAFIA', 'Ecografia'), ('ENFERMAGEM', 'Enfermagem'), ('PROCEDIMENTO', 'Procedimento'), ('CIRURGIA', 'Cirurgia'), ('MATERNIDADE', 'Maternidade'), ('MED_URGENCIA', 'Medicamento de Urgência'), ('MATERIAL_CLINICO', 'Material Clínico'), ('IMUNIZACAO', 'Imunização'), ('DOCUMENTO', 'Documento'), ('CARTAO', 'Cartão'), ('OBSERVACAO_CLINICA', 'Observação Clínica'), ('EXAME', 'Exame (legado)'), ('OUTRO', 'Outro'), ('INTERNAMENTO', 'Internamento (legado)')], default='OUTRO', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['departamento', 'activo'], name='idx_bill_svc_dept_act'),
        ),
        migrations.AddField(
            model_name='servicoprecohistorico',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_preco_servico', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='servicoprecohistorico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='billing.servico', verbose_name='Serviço'),
        ),
    ]
