# Generated by Django 5.1.15 on 2026-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_sprint18_1_reducao_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducaovalorautorizacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='reducaovalorautorizacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
