# Generated by Django 5.1.15 on 2026-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_sprint18_2_catalogo_v1_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='codigo',
            field=models.CharField(max_length=64, unique=True, verbose_name='Código'),
        ),
    ]
