# Generated by Django 5.1.15 on 2026-07-06 11:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_sprint8_fase1_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('estado', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='FECHADO', max_length=10, verbose_name='Estado')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo inicial')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo actual')),
                ('data_abertura', models.DateTimeField(blank=True, null=True, verbose_name='Data de abertura')),
                ('data_fecho', models.DateTimeField(blank=True, null=True, verbose_name='Data de fecho')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('utilizador_abertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertas', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador de abertura')),
                ('utilizador_fecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechadas', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador de fecho')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoria financeira',
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.CharField(max_length=150, verbose_name='Fornecedor')),
                ('categoria', models.CharField(choices=[('MEDICAMENTOS', 'Medicamentos'), ('EQUIPAMENTOS', 'Equipamentos'), ('MATERIAL_CLINICO', 'Material Clínico'), ('ENERGIA', 'Energia'), ('INTERNET', 'Internet'), ('AGUA', 'Água'), ('SALARIOS', 'Salários'), ('MANUTENCAO', 'Manutenção'), ('LIMPEZA', 'Limpeza'), ('OUTROS', 'Outros')], default='OUTROS', max_length=30, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15, verbose_name='Estado')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('categoria_financeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='finance.categoriafinanceira', verbose_name='Categoria financeira')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste')], max_length=15, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('PAGAMENTO', 'Pagamento'), ('DESPESA', 'Despesa'), ('CORRECCAO', 'Correcção'), ('MANUAL', 'Manual')], max_length=15, verbose_name='Origem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='finance.caixa', verbose_name='Caixa')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='finance.despesa', verbose_name='Despesa')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='billing.pagamento', verbose_name='Pagamento')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Movimento financeiro',
                'verbose_name_plural': 'Movimentos financeiros',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['estado', 'data'], name='idx_fin_desp_estado_data'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanceiro',
            index=models.Index(fields=['tipo', 'data'], name='idx_fin_mov_tipo_data'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanceiro',
            index=models.Index(fields=['caixa', 'data'], name='idx_fin_mov_caixa_data'),
        ),
    ]
