# Generated by Django 5.1.15 on 2026-07-03 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apelido')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECECIONISTA', 'Rececionista'), ('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro'), ('LABORATORIO', 'Laboratório'), ('FINANCEIRO', 'Financeiro')], default='RECECIONISTA', max_length=20, verbose_name='Perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de registo')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
