# Generated by Django 5.1.15 on 2026-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_birth_date_user_deleted_at_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECECIONISTA', 'Rececionista'), ('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro'), ('LABORATORIO', 'Laboratório'), ('FINANCEIRO', 'Financeiro'), ('DIRECTOR', 'Director')], default='RECECIONISTA', max_length=20, verbose_name='Perfil'),
        ),
    ]
