# Generated by Django 5.1.15 on 2026-07-03 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de check-in')),
                ('status', models.CharField(choices=[('WAITING', 'Em espera'), ('IN_CONSULTATION', 'Em consulta'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='WAITING', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('EMERGENCY', 'Emergência')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_check_ins', to='patients.patient', verbose_name='Paciente')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Rececionista')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('from_department', models.CharField(choices=[('RECEPTION', 'Receção'), ('DOCTOR', 'Médico'), ('LAB', 'Laboratório'), ('BILLING', 'Faturação')], default='RECEPTION', max_length=20, verbose_name='Departamento origem')),
                ('to_department', models.CharField(choices=[('RECEPTION', 'Receção'), ('DOCTOR', 'Médico'), ('LAB', 'Laboratório'), ('BILLING', 'Faturação')], max_length=20, verbose_name='Departamento destino')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='reception.receptioncheckin', verbose_name='Check-in')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patient', verbose_name='Paciente')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_created', to=settings.AUTH_USER_MODEL, verbose_name='Encaminhado por')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('position', models.PositiveIntegerField(verbose_name='Posição')),
                ('estimated_wait_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo estimado (min)')),
                ('status', models.CharField(choices=[('WAITING', 'Em espera'), ('CALLED', 'Chamado'), ('IN_SERVICE', 'Em atendimento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='WAITING', max_length=20, verbose_name='Estado')),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='reception.receptioncheckin', verbose_name='Check-in')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Fila de espera',
                'verbose_name_plural': 'Fila de espera',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receptioncheckin',
            index=models.Index(fields=['status', 'check_in_time'], name='idx_checkin_status_time'),
        ),
        migrations.AddIndex(
            model_name='receptioncheckin',
            index=models.Index(fields=['patient', 'status'], name='idx_checkin_patient_status'),
        ),
        migrations.AddIndex(
            model_name='receptioncheckin',
            index=models.Index(fields=['priority'], name='idx_checkin_priority'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'created_at'], name='idx_referral_patient_date'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['to_department'], name='idx_referral_to_dept'),
        ),
        migrations.AddIndex(
            model_name='waitingqueue',
            index=models.Index(fields=['status', 'position'], name='idx_queue_status_position'),
        ),
        migrations.AddIndex(
            model_name='waitingqueue',
            index=models.Index(fields=['patient', 'status'], name='idx_queue_patient_status'),
        ),
    ]
