# Generated by Django 5.1.15 on 2026-07-03 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('patient_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº processo')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apelido')),
                ('full_name', models.CharField(editable=False, max_length=201, verbose_name='Nome completo')),
                ('document_type', models.CharField(blank=True, choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte'), ('CARTAO_RESIDENTE', 'Cartão de residente'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Nº documento')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Morada')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_region', models.CharField(blank=True, max_length=100, verbose_name='Região')),
                ('address_country', models.CharField(blank=True, default='Guiné-Bissau', max_length=100, verbose_name='País')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('DESCONHECIDO', 'Desconhecido')], max_length=12, verbose_name='Grupo sanguíneo')),
                ('marital_status', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Estado civil')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Profissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('allergen', models.CharField(max_length=150, verbose_name='Alergénio')),
                ('severity', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('ANAFILAXIA', 'Anafilaxia')], default='MODERADA', max_length=20, verbose_name='Gravidade')),
                ('reaction', models.CharField(blank=True, max_length=255, verbose_name='Reação')),
                ('diagnosed_at', models.DateField(blank=True, null=True, verbose_name='Diagnosticado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allergies', to='patients.patient', verbose_name='Paciente')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_allergies_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'ordering': ['-severity', 'allergen'],
            },
        ),
        migrations.CreateModel(
            name='PatientChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disease_name', models.CharField(max_length=200, verbose_name='Doença')),
                ('icd_code', models.CharField(blank=True, max_length=20, verbose_name='Código CID')),
                ('diagnosed_at', models.DateField(blank=True, null=True, verbose_name='Diagnosticado em')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONTROLADA', 'Controlada'), ('REMISSAO', 'Remissão'), ('CURADA', 'Curada')], default='ATIVA', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chronic_diseases', to='patients.patient', verbose_name='Paciente')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chronic_diseases_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doença crónica',
                'verbose_name_plural': 'Doenças crónicas',
                'ordering': ['disease_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('document_type', models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte'), ('CARTAO_SEGURO', 'Cartão de seguro'), ('CONSENTIMENTO', 'Consentimento'), ('EXAME_EXTERNO', 'Exame externo'), ('DECLARACAO', 'Declaração'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Nº documento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Emitido em')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='patients.patient', verbose_name='Paciente')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patient_documents', to='files.storedfile', verbose_name='Ficheiro')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('relationship', models.CharField(choices=[('CONJUGE', 'Cônjuge'), ('PAI', 'Pai'), ('MAE', 'Mãe'), ('FILHO', 'Filho'), ('IRMAO', 'Irmão'), ('AMIGO', 'Amigo'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Parentesco')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contacts_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='emergency_contacts', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Contacto de emergência',
                'verbose_name_plural': 'Contactos de emergência',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REGISTO', 'Registo'), ('ADMISSAO', 'Admissão'), ('ALTA', 'Alta'), ('CONSULTA', 'Consulta'), ('EXAME', 'Exame'), ('DIAGNOSTICO', 'Diagnóstico'), ('CIRURGIA', 'Cirurgia'), ('MEDICACAO', 'Medicação'), ('ALERGIA', 'Alergia'), ('DOENCA_CRONICA', 'Doença crónica'), ('DOCUMENTO', 'Documento'), ('OBSERVACAO', 'Observação'), ('PAGAMENTO', 'Pagamento'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de evento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_date', models.DateTimeField(verbose_name='Data do evento')),
                ('source_module', models.CharField(blank=True, max_length=30, verbose_name='Módulo de origem')),
                ('source_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de origem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history_entries', to='patients.patient', verbose_name='Paciente')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_history_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider_name', models.CharField(max_length=150, verbose_name='Seguradora')),
                ('policy_number', models.CharField(max_length=50, verbose_name='Nº apólice')),
                ('plan_type', models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('COMPLETO', 'Completo'), ('EMPRESA', 'Empresa'), ('ESTADO', 'Estado'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de plano')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_insurances_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insurances', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'ordering': ['-is_primary', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('observation_type', models.CharField(choices=[('CLINICA', 'Clínica'), ('ENFERMAGEM', 'Enfermagem'), ('ADMINISTRATIVA', 'Administrativa')], max_length=20, verbose_name='Tipo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_observations_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='observations', to='patients.patient', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_observations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observação',
                'verbose_name_plural': 'Observações',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photos', to='patients.patient', verbose_name='Paciente')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patient_photos', to='files.storedfile', verbose_name='Imagem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fotografia',
                'verbose_name_plural': 'Fotografias',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='idx_patient_last_first'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='idx_patient_full_name'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['document_number'], name='idx_patient_document'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='idx_patient_phone'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_number'], name='idx_patient_number'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active', 'is_deleted'], name='idx_patient_active_del'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['birth_date'], name='idx_patient_birth_date'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__gt', '')), fields=('document_number',), name='patients_patient_unique_document'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient'], name='idx_allergy_patient'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['allergen'], name='idx_allergy_allergen'),
        ),
        migrations.AddConstraint(
            model_name='patientallergy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'allergen'), name='uniq_patient_allergen_active'),
        ),
        migrations.AddIndex(
            model_name='patientchronicdisease',
            index=models.Index(fields=['patient'], name='idx_chronic_patient'),
        ),
        migrations.AddIndex(
            model_name='patientchronicdisease',
            index=models.Index(fields=['icd_code'], name='idx_chronic_icd'),
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(fields=['patient', 'document_type'], name='idx_doc_patient_type'),
        ),
        migrations.AddIndex(
            model_name='patientemergencycontact',
            index=models.Index(fields=['patient', 'is_primary'], name='idx_emerg_patient_primary'),
        ),
        migrations.AddIndex(
            model_name='patienthistory',
            index=models.Index(fields=['patient', 'event_date'], name='idx_history_patient_date'),
        ),
        migrations.AddIndex(
            model_name='patienthistory',
            index=models.Index(fields=['event_type'], name='idx_history_event_type'),
        ),
        migrations.AddIndex(
            model_name='patienthistory',
            index=models.Index(fields=['source_module', 'source_id'], name='idx_history_source'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['patient', 'is_active'], name='idx_insurance_patient_active'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['policy_number'], name='idx_insurance_policy'),
        ),
        migrations.AddIndex(
            model_name='patientobservation',
            index=models.Index(fields=['patient', 'is_pinned'], name='idx_obs_patient_pinned'),
        ),
        migrations.AddIndex(
            model_name='patientobservation',
            index=models.Index(fields=['observation_type'], name='idx_obs_type'),
        ),
        migrations.AddIndex(
            model_name='patientphoto',
            index=models.Index(fields=['patient', 'is_primary'], name='idx_photo_patient_primary'),
        ),
    ]
