/** Textos de interface em Português (PT) — fonte única para consistência clínica. */
export const UI_COPY = {
  appName: "SauVida",
  appTagline: "Sistema de Gestão Clínica",
  analytics: "Análise Clínica SauVida",

  nav: {
    home: "Início",
    dashboard: "Painel",
    patients: "Pacientes",
    appointments: "Consultas",
    appointmentsSchedule: "Marcações",
    payments: "Pagamentos",
    receipts: "Recibos",
    doctors: "Médicos",
    laboratory: "Laboratório",
    billing: "Faturação",
    finance: "Financeiro",
    reports: "Relatórios",
    notifications: "Notificações",
    settings: "Definições",
    administration: "Administração",
    users: "Utilizadores",
    roles: "Perfis",
    monitoring: "Monitorização",
    audit: "Auditoria",
    backups: "Cópias de segurança",
    featureFlags: "Funcionalidades experimentais",
    checkIn: "Triagem",
    fastReception: "Atendimento rápido",
    queue: "Fila de espera",
    referrals: "Encaminhamentos",
    templates: "Modelos",
    preferences: "Preferências",
    history: "Histórico",
    center: "Centro",
    todayAppointments: "Consultas de Hoje",
    clinicalRecords: "Registos Clínicos",
    labResultsShort: "Resultados Lab.",
    followUps: "Seguimentos",
    results: "Resultados",
    pending: "Pendentes",
    collection: "Colheitas",
    reception: "Receção",
    features: "Funcionalidades",
  },

  actions: {
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    create: "Criar",
    delete: "Eliminar",
    search: "Pesquisar",
    filter: "Filtrar",
    export: "Exportar",
    print: "Imprimir",
    back: "Voltar",
    next: "Seguinte",
    previous: "Anterior",
    retry: "Tentar novamente",
    close: "Fechar",
    confirm: "Confirmar",
  },

  status: {
    active: "Activo",
    inactive: "Inactivo",
    pending: "Pendente",
    total: "Total",
    online: "Em linha",
  },

  clinical: {
    turnaround: "Tempo médio de resposta",
    validationTime: "Tempo de validação",
    checkInSuccess: "Entrada registada com sucesso.",
    newCheckIn: "Novo registo de entrada",
    performCheckIn: "Registar entrada",
    systemHealth: "Estado do sistema",
    cache: "Memória cache",
  },
} as const;

export const BREADCRUMB_LABELS: Record<string, string> = {
  admin: "Administração",
  dashboard: "Painel",
  patients: "Pacientes",
  reception: "Receção",
  appointments: "Consultas",
  consultations: "Consultas clínicas",
  laboratory: "Laboratório",
  results: "Resultados",
  billing: "Faturação",
  finance: "Financeiro",
  reports: "Relatórios",
  executive: "Executivo",
  settings: "Definições",
  doctor: "Médico",
  notifications: "Notificações",
  users: "Utilizadores",
  permissions: "Permissões",
  groups: "Grupos",
  audit: "Auditoria",
  profile: "Perfil",
  "check-in": "Registo de entrada",
  queue: "Fila",
  referrals: "Encaminhamentos",
  invoices: "Faturas",
  payments: "Pagamentos",
  receipts: "Recibos",
  quotes: "Orçamentos",
  services: "Serviços",
  pending: "Pendentes",
  collection: "Colheitas",
  today: "Processamento",
  templates: "Modelos",
  preferences: "Preferências",
  history: "Histórico",
  sms: "SMS",
  backups: "Cópias de segurança",
  "feature-flags": "Funcionalidades",
  system: "Sistema",
  security: "Segurança",
  clinic: "Clínica",
  departments: "Departamentos",
  specialties: "Especialidades",
  new: "Novo",
  edit: "Editar",
  cash: "Caixas",
  movements: "Movimentos",
  expenses: "Despesas",
  calendar: "Calendário",
  list: "Lista",
};
