# Generated by Django 5.1.15 on 2026-08-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_catalogo_v1_codigo_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('forma_apresentacao', models.CharField(blank=True, max_length=100, verbose_name='Forma')),
                ('unidade', models.CharField(default='unidade', max_length=30, verbose_name='Unidade')),
                ('quantidade_stock', models.PositiveIntegerField(default=0, verbose_name='Quantidade em stock')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos_urgencia', to='billing.servico', verbose_name='Serviço de faturação (opcional)')),
            ],
            options={
                'verbose_name': 'Medicamento de urgência',
                'verbose_name_plural': 'Medicamentos de urgência',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoStockUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste de inventário')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('quantidade_antes', models.PositiveIntegerField(verbose_name='Stock antes')),
                ('quantidade_depois', models.PositiveIntegerField(verbose_name='Stock depois')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='pharmacy.medicamentourgencia', verbose_name='Medicamento')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_farmacia_urgencia', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Movimento de stock (urgência)',
                'verbose_name_plural': 'Movimentos de stock (urgência)',
                'ordering': ['-created_at'],
            },
        ),
    ]
