# Generated by Django 5.1.15 on 2026-08-18 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_stock_urgencia_sprint22'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentourgencia',
            options={'ordering': ['nome'], 'verbose_name': 'Item de stock de urgência', 'verbose_name_plural': 'Itens de stock de urgência'},
        ),
        migrations.AlterModelOptions(
            name='movimentostockurgencia',
            options={'default_permissions': ('add', 'view'), 'ordering': ['-created_at'], 'verbose_name': 'Movimento de stock de urgência', 'verbose_name_plural': 'Movimentos de stock de urgência'},
        ),
        migrations.AlterField(
            model_name='medicamentourgencia',
            name='forma_apresentacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='medicamentourgencia',
            name='quantidade_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade actual'),
        ),
        migrations.AlterField(
            model_name='movimentostockurgencia',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='pharmacy.medicamentourgencia', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='movimentostockurgencia',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='movimentostockurgencia',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_farmacia_urgencia', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
    ]
