# Generated by Django 5.1.15 on 2026-07-06 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_pce_fase2'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('condicao', models.CharField(max_length=200, verbose_name='Condição')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('medicacao', models.TextField(blank=True, verbose_name='Medicação')),
                ('seguimento', models.TextField(blank=True, verbose_name='Seguimento')),
                ('restricoes', models.TextField(blank=True, verbose_name='Restrições')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alta_medica', to='appointments.appointment', verbose_name='Consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_medicas', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Alta médica',
                'verbose_name_plural': 'Altas médicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('MELHORIA', 'Melhoria'), ('AGRAVAMENTO', 'Agravamento'), ('ESTAVEL', 'Estável'), ('OBSERVACAO', 'Observação')], max_length=20, verbose_name='Tipo')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('resposta_tratamento', models.TextField(blank=True, verbose_name='Resposta ao tratamento')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas', to='appointments.appointment', verbose_name='Consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas', to='patients.patient', verbose_name='Paciente')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucoes_registadas', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Evolução clínica',
                'verbose_name_plural': 'Evoluções clínicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ACTIVA', 'Activa'), ('APROVADA', 'Aprovada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_medicas', to='appointments.appointment', verbose_name='Consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('objectivos', models.TextField(blank=True, verbose_name='Objectivos')),
                ('duracao_prevista', models.CharField(blank=True, max_length=100, verbose_name='Duração prevista')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_terapeuticos', to='appointments.appointment', verbose_name='Consulta')),
                ('prescricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='doctors.prescricao', verbose_name='Prescrição')),
            ],
            options={
                'verbose_name': 'Plano terapêutico',
                'verbose_name_plural': 'Planos terapêuticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoPrescrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('dosagem', models.CharField(max_length=100, verbose_name='Dosagem')),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, verbose_name='Forma farmacêutica')),
                ('via', models.CharField(blank=True, max_length=50, verbose_name='Via')),
                ('frequencia', models.CharField(max_length=100, verbose_name='Frequência')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('posologia', models.TextField(blank=True, verbose_name='Posologia')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENSO', 'Suspenso'), ('CONCLUIDO', 'Concluído')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='doctors.prescricao', verbose_name='Prescrição')),
            ],
            options={
                'verbose_name': 'Medicamento prescrito',
                'verbose_name_plural': 'Medicamentos prescritos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_prevista', models.DateField(verbose_name='Data prevista')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta_agendada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimento_clinico_origem', to='appointments.appointment', verbose_name='Consulta agendada')),
                ('consulta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimentos_clinicos', to='appointments.appointment', verbose_name='Consulta de origem')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimentos_clinicos', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimentos_clinicos', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Seguimento clínico',
                'verbose_name_plural': 'Seguimentos clínicos',
                'ordering': ['-data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('estado', models.CharField(choices=[('EM_CURSO', 'Em curso'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_CURSO', max_length=20, verbose_name='Estado')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamentos_medicos', to='appointments.appointment', verbose_name='Consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamentos', to='patients.patient', verbose_name='Paciente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
