# Generated by Django 5.1.15 on 2026-07-31 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_sprint16_catalogo'),
        ('clinic_settings', '0002_sprint10_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='especialidademedica',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Especialidade médica', 'verbose_name_plural': 'Especialidades médicas'},
        ),
        migrations.AlterModelOptions(
            name='tipoexamelaboratorio',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Tipo de exame laboratorial', 'verbose_name_plural': 'Tipos de exames laboratoriais'},
        ),
        migrations.AddField(
            model_name='configuracaofaturacao',
            name='numero_inicial_recibo',
            field=models.PositiveIntegerField(default=1, verbose_name='Número inicial recibo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='contactos_internos',
            field=models.TextField(blank=True, verbose_name='Contactos internos'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='horario',
            field=models.TextField(blank=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='localizacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='especialidademedica',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidades', to='clinic_settings.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='especialidademedica',
            name='duracao_consulta_minutos',
            field=models.PositiveIntegerField(default=30, verbose_name='Duração consulta (min)'),
        ),
        migrations.AddField(
            model_name='especialidademedica',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='perfilclinica',
            name='contacto_urgencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contacto de urgência'),
        ),
        migrations.AddField(
            model_name='perfilclinica',
            name='texto_legal',
            field=models.TextField(blank=True, verbose_name='Texto legal'),
        ),
        migrations.AddField(
            model_name='tipoexamelaboratorio',
            name='exige_jejum',
            field=models.BooleanField(default=False, verbose_name='Exige jejum'),
        ),
        migrations.AddField(
            model_name='tipoexamelaboratorio',
            name='instrucoes_colheita',
            field=models.TextField(blank=True, verbose_name='Instruções de colheita'),
        ),
        migrations.AddField(
            model_name='tipoexamelaboratorio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='tipoexamelaboratorio',
            name='recipiente',
            field=models.CharField(blank=True, max_length=80, verbose_name='Recipiente'),
        ),
        migrations.AddField(
            model_name='tipoexamelaboratorio',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_exame_laboratorio', to='billing.servico', verbose_name='Serviço de faturação'),
        ),
        migrations.AddField(
            model_name='tipoexamelaboratorio',
            name='tipo_amostra',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo de amostra'),
        ),
        migrations.CreateModel(
            name='MedicoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_profissional', models.CharField(blank=True, max_length=50, verbose_name='Número profissional')),
                ('dias_trabalho', models.JSONField(blank=True, default=list, verbose_name='Dias de trabalho')),
                ('horario_atendimento', models.JSONField(blank=True, default=dict, verbose_name='Horário de atendimento')),
                ('duracao_consulta_minutos', models.PositiveIntegerField(default=30, verbose_name='Duração consulta (min)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('disponivel_marcacao', models.BooleanField(default=True, verbose_name='Disponível para marcação')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='clinic_settings.departamento', verbose_name='Departamento')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='clinic_settings.especialidademedica', verbose_name='Especialidade')),
                ('servico_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos_consulta', to='billing.servico', verbose_name='Serviço de consulta')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Perfil médico',
                'verbose_name_plural': 'Perfis médicos',
            },
        ),
    ]
