# Generated by Django 5.1.15 on 2026-07-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_pce_fase2'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_pedido', models.CharField(max_length=20, unique=True, verbose_name='Número do pedido')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('AGUARDANDO_COLHEITA', 'Aguardando colheita'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=25, verbose_name='Estado')),
                ('prioridade', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('EMERGENCY', 'Emergência')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido')),
                ('data_rececao', models.DateTimeField(blank=True, null=True, verbose_name='Data de receção')),
                ('data_colheita', models.DateTimeField(blank=True, null=True, verbose_name='Data de colheita')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_laboratoriais', to='appointments.appointment', verbose_name='Consulta')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_laboratoriais_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_laboratoriais', to='patients.patient', verbose_name='Paciente')),
                ('pedido_consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_laboratorial', to='appointments.pedidolaboratorio', verbose_name='Pedido na consulta')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_lab_registados', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Pedido laboratorial',
                'verbose_name_plural': 'Pedidos laboratoriais',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ExameLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_exame', models.CharField(max_length=150, verbose_name='Nome do exame')),
                ('categoria', models.CharField(choices=[('HEMATOLOGIA', 'Hematologia'), ('BIOQUIMICA', 'Bioquímica'), ('MICROBIOLOGIA', 'Microbiologia'), ('IMUNOLOGIA', 'Imunologia'), ('GERAL', 'Geral')], default='GERAL', max_length=30, verbose_name='Categoria')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('AGUARDANDO_COLHEITA', 'Aguardando colheita'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=25, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='laboratory.pedidolaboratorial', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Exame laboratorial',
                'verbose_name_plural': 'Exames laboratoriais',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidolaboratorial',
            index=models.Index(fields=['estado', 'data_pedido'], name='idx_lab_ped_estado_data'),
        ),
        migrations.AddIndex(
            model_name='pedidolaboratorial',
            index=models.Index(fields=['paciente', 'data_pedido'], name='idx_lab_ped_paciente'),
        ),
        migrations.AddIndex(
            model_name='pedidolaboratorial',
            index=models.Index(fields=['numero_pedido'], name='idx_lab_ped_numero'),
        ),
    ]
