# Generated by Django 5.1.15 on 2026-07-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('laboratory', '0001_sprint7_fase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estado', models.CharField(choices=[('EM_PROCESSAMENTO', 'Em processamento'), ('RESULTADO_PENDENTE', 'Resultado pendente'), ('VALIDADO', 'Validado'), ('ENTREGUE', 'Entregue')], default='EM_PROCESSAMENTO', max_length=25, verbose_name='Estado')),
                ('data_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Data do resultado')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de validação')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('conclusao', models.TextField(blank=True, verbose_name='Conclusão')),
                ('pedido_laboratorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='laboratory.pedidolaboratorial', verbose_name='Pedido laboratorial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_laboratoriais', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Resultado laboratorial',
                'verbose_name_plural': 'Resultados laboratoriais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParametroResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('unidade', models.CharField(blank=True, max_length=30, verbose_name='Unidade')),
                ('valor_minimo', models.CharField(blank=True, max_length=30, verbose_name='Valor mínimo')),
                ('valor_maximo', models.CharField(blank=True, max_length=30, verbose_name='Valor máximo')),
                ('interpretacao', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTO', 'Alto'), ('BAIXO', 'Baixo'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=20, verbose_name='Interpretação')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='laboratory.resultadolaboratorial', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Parâmetro de resultado',
                'verbose_name_plural': 'Parâmetros de resultado',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('JPEG', 'JPEG'), ('DOCX', 'DOCX')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ficheiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_resultado_laboratorial', to='files.storedfile', verbose_name='Ficheiro')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='laboratory.resultadolaboratorial', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Anexo de resultado',
                'verbose_name_plural': 'Anexos de resultado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resultadolaboratorial',
            index=models.Index(fields=['estado', 'data_resultado'], name='idx_lab_res_estado_data'),
        ),
    ]
